repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - '--py38-plus'
        name: Upgrade syntax

  - repo: 'https://github.com/hadialqattan/pycln'
    rev: v2.1.2
    hooks:
      - id: pycln
        args:
          - '--config=pyproject.toml'
        name: Remove unused imports

  - repo: 'https://github.com/psf/black'
    rev: 22.10.0
    hooks:
      - id: black

  - repo: 'https://github.com/pycqa/isort'
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v0.961
    hooks:
      - id: mypy
        exclude: ^tests/|^docs

  - repo: 'https://github.com/pycqa/flake8'
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^tests/|^docs/
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
          - flake8-pie
          - flake8-type-checking
          - flake8-annotations
